#pragma once

#define RESET_TEXT WHITE_COLOUR,LIGHT,TEXT
#define RESET_BACKGROUND BLACK_COLOUR,DARK,BACKGROUND

#define BOARD_DARK_BACKGROUND YELLOW_COLOUR,LIGHT,BACKGROUND
#define BOARD_LIGHT_BACKGROUND WHITE_COLOUR,LIGHT,BACKGROUND
#define GRID_TEXT MAGENTA_COLOUR,LIGHT,TEXT

#define WHITE_TEAM_TEXT GREEN_COLOUR,DARK,TEXT
#define BLACK_TEAM_TEXT RED_COLOUR,DARK,TEXT

//These enums are ordered for calculating numbers used for ANSI colour codes
typedef enum { BLACK_COLOUR, RED_COLOUR, GREEN_COLOUR, YELLOW_COLOUR, BLUE_COLOUR, MAGENTA_COLOUR, CYAN_COLOUR, WHITE_COLOUR } Colour;
typedef enum { DARK, LIGHT } Brightness;
typedef enum { TEXT, BACKGROUND } Selection;

#define COLOUR_APPLY_STRING_SHAPE "\033[123m"
#define COLOUR_RESET_STRING_SHAPE COLOUR_APPLY_STRING_SHAPE COLOUR_APPLY_STRING_SHAPE
char* colourf(Colour c, Brightness b, Selection s);
char* resetf();	//resets text colour AND background colour